language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn workspace @nehalist/gatsby-theme-nehalem lint
  - yarn workspace demo build
